# Generated by Django 5.2.8 on 2025-11-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Вес товара в граммах', max_digits=8, verbose_name='Вес (г)'),
        ),
    ]
