# Generated by Django 5.2.8 on 2025-11-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_currency_order_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping cost'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping cost in base currency (RUB)'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Shipping method'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total weight (g)'),
        ),
    ]
